package mrnoerglugger.beeginning.setup;

import static mrnoerglugger.beeginning.items.bees.AdvancedBee.registerAdvancedBee;
import static mrnoerglugger.beeginning.items.bees.AurumBee.registerAurumBee;
import static mrnoerglugger.beeginning.items.bees.BaobabBee.registerBaobabBee;
import static mrnoerglugger.beeginning.items.bees.BetulaBee.registerBetulaBee;
import static mrnoerglugger.beeginning.items.bees.BloomingBee.registerBloomingBee;
import static mrnoerglugger.beeginning.items.bees.CarboBee.registerCarboBee;
import static mrnoerglugger.beeginning.items.bees.CavingBee.registerCavingBee;
import static mrnoerglugger.beeginning.items.bees.CrimsonBee.registerCrimsonBee;
import static mrnoerglugger.beeginning.items.bees.CrystalBee.registerCrystalBee;
import static mrnoerglugger.beeginning.items.bees.CuprumBee.registerCuprumBee;
import static mrnoerglugger.beeginning.items.bees.DeltaBee.registerDeltaBee;
import static mrnoerglugger.beeginning.items.bees.DryBee.registerDryBee;
import static mrnoerglugger.beeginning.items.bees.EngineeredBee.registerEngineeredBee;
import static mrnoerglugger.beeginning.items.bees.ExtraordinaryBee.registerExtraordinaryBee;
import static mrnoerglugger.beeginning.items.bees.FerrumBee.registerFerrumBee;
import static mrnoerglugger.beeginning.items.bees.FinalisBee.registerFinalisBee;
import static mrnoerglugger.beeginning.items.bees.FreezingBee.registerFreezingBee;
import static mrnoerglugger.beeginning.items.bees.GlowingBee.registerGlowingBee;
import static mrnoerglugger.beeginning.items.bees.LazuriteBee.registerLazuriteBee;
import static mrnoerglugger.beeginning.items.bees.MesaBee.registerMesaBee;
import static mrnoerglugger.beeginning.items.bees.MiraculousBee.registerMiraculousBee;
import static mrnoerglugger.beeginning.items.bees.MorassBee.registerMorassBee;
import static mrnoerglugger.beeginning.items.bees.MountainousBee.registerMountainousBee;
import static mrnoerglugger.beeginning.items.bees.NoteworthyBee.registerNoteworthyBee;
import static mrnoerglugger.beeginning.items.bees.OrdinaryBee.registerOrdinaryBee;
import static mrnoerglugger.beeginning.items.bees.PlainBee.registerPlainBee;
import static mrnoerglugger.beeginning.items.bees.PrimordialBee.registerPrimordialBee;
import static mrnoerglugger.beeginning.items.bees.SeaBee.registerSeaBee;
import static mrnoerglugger.beeginning.items.bees.ShiningBee.registerShiningBee;
import static mrnoerglugger.beeginning.items.bees.ShroomyBee.registerShroomyBee;
import static mrnoerglugger.beeginning.items.bees.SilicaBee.registerSilicaBee;
import static mrnoerglugger.beeginning.items.bees.SmaragdusBee.registerSmaragdusBee;
import static mrnoerglugger.beeginning.items.bees.SnowingBee.registerSnowingBee;
import static mrnoerglugger.beeginning.items.bees.ThicketBee.registerThicketBee;
import static mrnoerglugger.beeginning.items.bees.TwilightBee.registerTwilightBee;
import static mrnoerglugger.beeginning.items.bees.ValleyBee.registerValleyBee;
import static mrnoerglugger.beeginning.items.bees.VoidBee.registerVoidBee;
import static mrnoerglugger.beeginning.items.bees.WarpedBee.registerWarpedBee;
import static mrnoerglugger.beeginning.items.bees.WastingBee.registerWastingBee;
import static mrnoerglugger.beeginning.items.bees.WoodlandBee.registerWoodlandBee;

public class BeeRegistry {
    public static void registerBees() {
        registerPlainBee();
        registerWoodlandBee();
        registerBetulaBee();
        registerTwilightBee();
        registerThicketBee();
        registerSnowingBee();
        registerBaobabBee();
        registerWarpedBee();
        registerCrimsonBee();
        registerShroomyBee();
        registerDryBee();
        registerMesaBee();
        registerMorassBee();
        registerBloomingBee();
        registerSeaBee();
        registerFreezingBee();
        registerMountainousBee();
        registerCavingBee();
        registerWastingBee();
        registerValleyBee();
        registerDeltaBee();
        registerFinalisBee();
        registerVoidBee();
        registerOrdinaryBee();
        registerAdvancedBee();
        registerNoteworthyBee();
        registerExtraordinaryBee();
        registerMiraculousBee();
        registerCarboBee();
        registerGlowingBee();
        registerCuprumBee();
        registerFerrumBee();
        registerSilicaBee();
        registerEngineeredBee();
        registerAurumBee();
        registerLazuriteBee();
        registerCrystalBee();
        registerShiningBee();
        registerSmaragdusBee();
        registerPrimordialBee();
    }
}
